
name: Release

on:
  push:
    tags:
      - 'v*' # Trigger wird ausgelöst, wenn ein Tag gepusht wird, der mit 'v' beginnt (z.B. v1.0.0)

permissions:
  contents: write # Wichtig: Erlaubt der Action, Releases und Artefakte hochzuladen

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wichtig für das automatische Changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Deine genutzte Go-Version
          cache: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Wird automatisch von GitHub bereitgestellt